# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
   
      - name: cd to dir
        run: dir
      - name: Install Dependencies
        working-directory: ./kommentar-app
        run: npm install
      - name: Build
        working-directory: ./kommentar-app
        run: npm run build
      - name: use tool
        working-directory: ./kommentar-app
        run: npm install firebase-tools
      - name: Deploy to Firebase
        working-directory: ./kommentar-app
        run: firebase deploy --token "${{ secrets.FirebaseDeploy }}" --only hosting
   
     
